linear:
  fit_intercept: true

tree:
  max_depth: 5
  random_state: 42

catboost:
  iterations: 500
  learning_rate: 0.1
  depth: 6
  random_seed: 42
  verbose: 0

xgboost:
  n_estimators: 500
  learning_rate: 0.1
  max_depth: 6
  random_state: 42

mlp:
  hidden_layer_sizes: [64, 32]
  activation: relu
  solver: adam
  max_iter: 500
  random_state: 42
  alpha: 0.001
